FROM node:19-alpine AS build
WORKDIR /node
COPY package*.json tsconfig.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM nginx:1.23-alpine
COPY --from=build /node/dist/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/
ENTRYPOINT ["nginx", "-g", "daemon off;"]

