services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      go-app:
        condition: service_started
    ports:
    - target: 5173
      published: "5173"
    volumes:
    - type: bind
      source: ./client
      target: /node/app
      consistency: delegated
    - type: volume
      target: /node/app/node_modules
  go-app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    depends_on:
      redis-storage-0:
        condition: service_started
      redis-storage-1:
        condition: service_started
      redis-storage-2:
        condition: service_started
    environment:
      REDIS_CONFIG: '[{"name":"redis-storage-0","port":6379,"password":"redis-storage-0"},{"name":"redis-storage-1","port":6379,"password":"redis-storage-1"},{"name":"redis-storage-2","port":6379,"password":"redis-storage-2"}]'
    ports:
    - target: 8000
      published: "8000"
    volumes:
    - type: bind
      source: ./app
      target: /app
      consistency: delegated
  redis-storage-0:
    command:
    - redis-server
    - --save
    - "20"
    - "1"
    - --loglevel
    - warning
    - --requirepass
    - redis-storage-0
    image: redis:7.0-alpine
    restart: always
  redis-storage-1:
    command:
    - redis-server
    - --save
    - "20"
    - "1"
    - --loglevel
    - warning
    - --requirepass
    - redis-storage-1
    image: redis:7.0-alpine
    restart: always
  redis-storage-2:
    command:
    - redis-server
    - --save
    - "20"
    - "1"
    - --loglevel
    - warning
    - --requirepass
    - redis-storage-2
    image: redis:7.0-alpine
    restart: always
