FROM golang:1.20-alpine  as builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go install github.com/cespare/reflex@latest
CMD reflex -g '**/*.go' go run main.go --start-service
